[package]
name = "cf"
version = "0.1.0"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
edgeworker-sys = { path = "../../edgeworker-sys" }
quote = "1.0.9"
syn = "1.0.72"
wasm-bindgen-macro-support = "0.2.74"
web-sys = "0.3.51"
worker = { path = "../../worker" }
durable_object = { path = "../durable_object" }