[package]
name = "worker"
version = "0.1.0"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs"
edition = "2018"
keywords = ["serverless", "ffi", "workers", "wasm", "cloudflare"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
edgeworker-sys = { path = "../edgeworker-sys" }
js-sys = "0.3.53"
libworker = { path = "../libworker" }
macros = { path = "../macros" }
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.24"