[package]
name = "worker"
version = "0.1.0"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs"
edition = "2018"
keywords = ["serverless", "ffi", "workers", "wasm", "cloudflare"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edgeworker-ffi = { path = "../edgeworker-ffi" }
js-sys = "0.3.51"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
url = "2.2.2"
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4.24"
worker-kv = "0.3.0"
web-sys = { version = "0.3.51", features = ["console"] }
http = "0.2.4"
matchit = "0.4.2"
async-trait = "0.1.50"
futures = "0.3.16"

[dev-dependencies]
wasm-bindgen-test = "0.3.24"
