[package]
name = "worker"
version = "0.0.1"
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
repository = "https://github.com/cloudflare/workers-rs"
edition = "2018"
keywords = ["serverless", "ffi", "workers", "wasm", "cloudflare"]
license = "Apache-2.0"
description = "A Rust SDK for writing Cloudfare Workers."
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
edgeworker-sys = { path = "../edgeworker-sys", version = "0.0.1" }
js-sys = "0.3.53"
libworker = { path = "../libworker", version = "0.0.1" }
workers-rs-macros = { path = "../macros", version = "0.0.1" }
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.24"